### ISSUE TITLE
[Bug]: [Paper 1.19.4] GriefPrevention integration: Jukebox only plays 11 with custom discs outside claimed zone, works fine inside claim.

### ISSUE THREAD

**Issue by upro2006** [spartacus04/jext-reborn#150]
### Describe the bug

Our server has GriefPrevention installed and it works as intended. However, JEXT Reborn discs somehow cannot be played properly (only play 11) outside claimed lands. Playing inside claimed/trusted land works fine.

These are my plugins:
![image](https://github.com/spartacus04/jext-reborn/assets/90815257/9cc11a0d-3f01-4be7-9cd6-59fe31744e4b)

### Steps to reproduce

1. Place a jukebox **outside claimed land**
2. Insert the custom music disc [Error appears in console after this step, shown in the _'Logs'_ part of this issue]
3. 11 plays instead of the custom song

### Expected behaviour

Custom song should play in step 3.

### Logs

[15:21:14 ERROR]: Could not pass event PlayerInteractEvent to JukeboxExtendedReborn v1.2.2 java.lang.NullPointerException: Cannot invoke "me.ryanhamshire.GriefPrevention.Claim.checkPermission(org.bukkit.entity.Player, me.ryanhamshire.GriefPrevention.ClaimPermission, org.bukkit.event.Event)" because "claim" is null         at me.spartacus04.jext.integrations.GriefPreventionIntegration.canInteract(GriefPreventionIntegration.kt:45) ~[JEXT-Reborn_1.2.2.jar:?]         at me.spartacus04.jext.integrations.GriefPreventionIntegration.canInteractWithJukebox(GriefPreventionIntegration.kt:31) ~[JEXT-Reborn_1.2.2.jar:?]         at me.spartacus04.jext.integrations.IntegrationsRegistrant$Companion.hasJukeboxAccess(IntegrationsRegistrant.kt:38) ~[JEXT-Reborn_1.2.2.jar:?]         at me.spartacus04.jext.listener.JukeboxEventListener.defaultBehaviour(JukeboxEventListener.kt:52) ~[JEXT-Reborn_1.2.2.jar:?]         at me.spartacus04.jext.listener.JukeboxEventListener.onJukeboxInteract(JukeboxEventListener.kt:39) ~[JEXT-Reborn_1.2.2.jar:?]         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor405.execute(Unknown Source) ~[?:?]         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]         at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server Version

1.19.4

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hi, thanks for the bug report, i just fixed this i'll now publish an update with the fix
