### ISSUE TITLE
[Bug]:The song will change music and report an error after 70 seconds

### ISSUE THREAD

**Issue by 347180440** [spartacus04/jext-reborn#216]
### Describe the bug

[06:10:41 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:60) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getNMS(CraftBlock.java:80) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getState(CraftBlock.java:343) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getCompound(NBTEditor.java:795) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getBlockTag(NBTEditor.java:785) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getValue(NBTEditor.java:943) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getLong(NBTEditor.java:1048) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.disc.DiscContainer.play$lambda$4(DiscContainer.kt:161) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.dependencies.jext-reborn.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58) ~[JEXT-Reborn_1.2.8.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[molia-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[molia-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:299) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:154) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:10:41 WARN]: java.lang.IllegalStateException: Cannot read world asynchronously
[06:10:41 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:61)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getNMS(CraftBlock.java:80)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getState(CraftBlock.java:343)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getCompound(NBTEditor.java:795)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getBlockTag(NBTEditor.java:785)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getValue(NBTEditor.java:943)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getLong(NBTEditor.java:1048)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.disc.DiscContainer.play$lambda$4(DiscContainer.kt:161)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:299)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:154)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406)
[06:10:41 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540)
[06:10:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:10:41 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:60) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getNMS(CraftBlock.java:80) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getState(CraftBlock.java:343) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.setBlockTag(NBTEditor.java:872) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.set(NBTEditor.java:1256) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.disc.DiscContainer.play$lambda$4(DiscContainer.kt:162) ~[JEXT-Reborn_1.2.8.jar:?]
        at me.spartacus04.jext.dependencies.jext-reborn.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58) ~[JEXT-Reborn_1.2.8.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[molia-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[molia-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:299) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:154) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:10:41 WARN]: java.lang.IllegalStateException: Cannot read world asynchronously
[06:10:41 WARN]:        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:61)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getNMS(CraftBlock.java:80)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231)
[06:10:41 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getState(CraftBlock.java:343)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.setBlockTag(NBTEditor.java:872)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.set(NBTEditor.java:1256)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.disc.DiscContainer.play$lambda$4(DiscContainer.kt:162)
[06:10:41 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:299)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:154)
[06:10:41 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406)
[06:10:41 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540)
[06:10:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
>

### Steps to reproduce

![image](https://github.com/spartacus04/jext-reborn/assets/107541071/841e9320-3fd6-42e4-9321-1178fdbffdf4)
Here do the loop playback device

### Expected behaviour

The test comes with purpur / folia

### Server Version

1.20.1

### Server Type

Folia

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by fligro** [comment]
Just encountered this same bug on a Paper 1.20.4 server. Didn't throw the error described, but all discs will play for 72 seconds before being pulled by the hopper, regardless of song length. Running JEXT 1.2.8, and ProtocolLib 5.2.0-Snapshot-679.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
