### ISSUE TITLE
[Bug]: Error in console

### ISSUE THREAD

**Issue by Gavin-Krikstone** [spartacus04/jext-reborn#244]
### Describe the bug

Everytime a player puts a disc in I get this error.
This error does not effect the playing of the music disc. But this error for some reason goes in console. This does not effect players in any way/

[22:31:05 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because the return value of "me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getMethod(String)" is null
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getCompound(NBTEditor.java:802)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getBlockTag(NBTEditor.java:785)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getValue(NBTEditor.java:943)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.dependencies.jext-reborn.nbteditor.NBTEditor.getLong(NBTEditor.java:1048)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.disc.DiscPlayer$Companion.stop(DiscPlayer.kt:64)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.disc.DiscContainer.play(DiscContainer.kt:144)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.disc.DiscContainer.play$default(DiscContainer.kt:142)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.listener.JukeboxEventListener.defaultBehaviour(JukeboxEventListener.kt:67)
[22:31:05 WARN]:        at JEXT-Reborn_1.2.8.jar//me.spartacus04.jext.listener.JukeboxEventListener.onJukeboxInteract(JukeboxEventListener.kt:40)
[22:31:05 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor463.execute(Unknown Source)
[22:31:05 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[22:31:05 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[22:31:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:31:05 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:31:05 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:31:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[22:31:05 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592)
[22:31:05 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:538)
[22:31:05 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2009)
[22:31:05 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[22:31:05 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[22:31:05 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[22:31:05 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:31:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:31:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[22:31:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1465)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1388)
[22:31:05 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1366)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1255)
[22:31:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:31:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

### Steps to reproduce

1. Put disc in jukebox
2. look in console

### Expected behaviour

No error

### Server Version

1.20.1

### Server Type

Purpur

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, thanks for submitting this bug report, I've just published a new update which should fix your bug.
