### ISSUE TITLE
Creeper-related NullPointerException in server log

### ISSUE THREAD

**Issue by marcelschoen** [spartacus04/jext-reborn#27]
I noticed the following exceptions randomly popping up in my server log (I wasn't doing anything with a jukebox or with music at all):

```[19:07:46 ERROR]: Could not pass event EntityDeathEvent to JukeboxExtendedReborn v0.6.3b
java.lang.NullPointerException: null
	at me.spartacus04.jext.listener.CreeperDeathListener.onCreeperDeath(CreeperDeathListener.kt:15) ~[JEXT-Reborn_0.6.3b.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor404.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-211]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:878) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1751) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1648) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:124) ~[paper-1.19.2.jar:git-Paper-211]
	at pl.minecon724.giants.Main.entityDeath(Main.java:189) ~[giants-22.10.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor428.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-211]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:878) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1751) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1648) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:403) ~[?:?]
	at net.minecraft.world.entity.Mob.baseTick(Mob.java:329) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.2.jar:git-Paper-211]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2934) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1190) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:728) ~[?:?]
```

I do have a ton of other plugins, including mob-related ones like "LevelledMobs", so maybe there's some interference.

**Comment by spartacus04** [comment]
Hi, I can't seem to replicate the bug, I even tried installing the LevelledMobs plugin but no error.
In the error you sent i'm noticing a mention to a pl.minecon724.giants plugin, I think that plugin may be causing the issue.
Do you mind sending that plugin download link, as I can't find it?

**Comment by mschoenUsp** [comment]
Writing from my secondary Github account here... this should be the plugin: https://www.spigotmc.org/resources/giants.99600/

**Comment by spartacus04** [comment]
Fixed in latest release
