### ISSUE TITLE
Plugin doesn’t start on launch

### ISSUE THREAD

**Issue by jaybruh** [spartacus04/jext-reborn#29]
whenever I start the plugin, I get the following error:

`[09:24:29] [Server thread/ERROR]: Could not load 'plugins/JEXT-Reborn_0.6.5b.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:411) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:319) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-220]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-220]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-220]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-220]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at me.spartacus04.jext.Log.<init>(Log.kt) ~[JEXT-Reborn_0.6.5b.jar:?]
	at me.spartacus04.jext.Log.<init>(Log.kt:10) ~[JEXT-Reborn_0.6.5b.jar:?]
	at me.spartacus04.jext.Jext.<clinit>(Jext.kt:66) ~[JEXT-Reborn_0.6.5b.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.spartacus04.jext.Log.<init>(Log.kt) ~[JEXT-Reborn_0.6.5b.jar:?]
	at me.spartacus04.jext.Log.<init>(Log.kt:10) ~[JEXT-Reborn_0.6.5b.jar:?]
	at me.spartacus04.jext.Jext.<clinit>(Jext.kt:66) ~[JEXT-Reborn_0.6.5b.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 7 more`

**Comment by jaybruh** [comment]
I’m using latest dev build of protocolLib, Build #602

**Comment by spartacus04** [comment]
Fixed in latest version, sorry about that.
