### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractEvent to JukeboxExtendedReborn v2.0.2 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Delitel-WEB** [spartacus04/jext-reborn#296]
### Describe the bug

when opening the chest, the disks do not spawn and an error occurs

### Steps to reproduce

1. open chest

### Expected behaviour

The disks should be spawned

### Logs

[22:02:57 ERROR]: Could not pass event PlayerInteractEvent to JukeboxExtendedReborn v2.0.2 java.lang.NullPointerException: null         at me.spartacus04.jext.listeners.ChestOpenEvent.generateItems(Unknown Source) ~[JEXT-Reborn_2.0.2.jar:?]         at me.spartacus04.jext.listeners.ChestOpenEvent.onChestOpen(Unknown Source) ~[JEXT-Reborn_2.0.2.jar:?]         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-478]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-478]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-478]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1935) ~[?:?]         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-478]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-478]         at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Server Version

1.20.4

### Server Type

Paper

### Discs.json

```json
[
  {
    "title": "ЧСВ",
    "author": "Pirate",
    "creeper-drop": true,
    "model-data": 1,
    "disc-namespace": "pirateone",
    "loot-tables": {
      "chests/village/village_plains_house": 1000,
      "chests/village/village_savanna_house": 1000,
      "chests/village/village_desert_house": 1000,
      "chests/village/village_snowy_house": 1000,
      "chests/village/village_taiga_house": 1000
    },
    "fragment-loot-tables": {},
    "duration": 201,
    "lores": []
  },
  {
    "title": "Педро",
    "author": "",
    "creeper-drop": true,
    "model-data": 2,
    "disc-namespace": "two",
    "loot-tables": {
      "chests/shipwreck_map": 300,
      "chests/shipwreck_supply": 300,
      "chests/shipwreck_treasure": 300,
      "chests/village/village_plains_house": 200,
      "chests/village/village_savanna_house": 200,
      "chests/village/village_desert_house": 200,
      "chests/village/village_snowy_house": 200,
      "chests/village/village_taiga_house": 200
    },
    "fragment-loot-tables": {},
    "duration": 124,
    "lores": []
  }
]
```

### Resource pack

https://download.mc-packs.net/pack/0c626216735afdca0e9af13caa397208ac2214b6.zip

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Fixed in https://github.com/spartacus04/jext-reborn/commit/80c6cd62e613431a5620da5ef4186f366b0d1a5e, it'll be published once https://github.com/spartacus04/jext-reborn/pull/301 is merged
