### ISSUE TITLE
[Bug]: Bugs of [Apply to your Jext server] 

### ISSUE THREAD

**Issue by Linf9** [spartacus04/jext-reborn#312]
### Describe the bug

plugin version is 2.0.4
After create a disc on webgui, and finished. Its normal for [download the resource pack for java edition], but the Microsorft Edge prompt that the spartacus04.github.io said TypeError: Failed to fetch by doing [apply to your jext server]. And there isnt the new disc in server. There is cmd logs afrer i pressed [Apply to your JEXT server]
[09:17:47 WARN]: Exception in thread "DefaultDispatcher-worker-4" java.util.zip.ZipException: zip END header not found
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1634)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1642)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1442)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
[09:17:47 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:195)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.discs.sources.file.FileSource$unpackResourcePack$2.invokeSuspend(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.DispatchedTask.run(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source)
[09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source)
[09:17:47 WARN]:        Suppressed: me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@13056e95, Dispatchers.Default]
On version 2.0.3, the bugs on webgui still exist, but the new disc is normally generated in server(jextadmingui)

Also the jext of folder seems different between 2.0.3 and 2.0.4. On 2.0.3, the folder contain [.savedata] but nothing on it anymore, [config.json] and [resource-pack.zip] formed automatically, but on 2.0.4 there is [cashes] folder more which is nothing neither after i created new disc same like [.savedata]. 

The server was running in China, which cannot connect the github stably. So i tried to host on other resource-hoster, on 2.0.3 after creating a disc, when i turn off [Enable resource pack host] the new disc disappear in jextadmingui. I dont try to test if it still on webgui since everytime i restart server, allthings on webgui are refreshed.

### Steps to reproduce

just put plugin in plugins folder, and do like steps.

### Expected behaviour

run normally

### Logs

[09:17:47 WARN]: Exception in thread "DefaultDispatcher-worker-4" java.util.zip.ZipException: zip END header not found [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1634) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1642) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1442) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181) [09:17:47 WARN]:        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:195) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.discs.sources.file.FileSource$unpackResourcePack$2.invokeSuspend(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.DispatchedTask.run(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source) [09:17:47 WARN]:        at JEXT-Reborn_2.0.4 (1).jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source) [09:17:47 WARN]:        Suppressed: me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@13056e95, Dispatchers.Default]

### Server Version

1.20.4

### Server Type

Folia

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment]
Hello, you can try deleting the cache directory in the plugin folder and update the plugin
