### ISSUE TITLE
[Bug]: Can't connect to Jext server

### ISSUE THREAD

**Issue by SamSamSam1999** [spartacus04/jext-reborn#376]
### Describe the bug

Can't connect to my Jext server, Apparently everything is running ok with the exception of

[11:46:11 WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.NoSuchFieldError: HIDE_ADDITIONAL_TOOLTIP
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.discs.sources.file.FileDisc.getDiscItemStack(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.discs.sources.file.FileDisc.toJextDisc(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.discs.sources.file.FileSource.getDiscs(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.discs.sources.file.FileSource$getDiscs$1.invokeSuspend(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.DispatchedTask.run(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source)
[11:46:11 WARN]:        at JEXT-Reborn_2.0.8.jar//me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source)
[11:46:11 WARN]:        Suppressed: me.spartacus04.jext.dependencies.jext-reborn.kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@496d5876, Dispatchers.Default]

This error pops on console when starting the server, however, the message of 
[JEXT] Enabled Jukebox Extended Reborn, Do Re Mi!
and
[JEXT] Webserver started on port ***** 
Appears normally, and the resourcepack I created without the WebGUI being connect is being applied to players, but when I try to connect to the Jext server usint the app an error appears

TypeError: Failed to fetch
    at window.fetch (http://tauri.localhost/_app/immutable/chunks/entry.OnfXmcHU.js:1:1667)
    at nd (http://tauri.localhost/_app/immutable/chunks/extensions.gJr_hkl8.js:19:30153)

### Steps to reproduce

download plugin, run server, edit config to port, edit password, create resourcepack.zip unconnected, change resourcepack name to resource-pack.zip, upload to server, try to connect to Jext server

Might have forgot some steps or misplaced the order

### Expected behaviour

Jext server joins upon typing right credentials

### Server Version

1.20.1

### Server Type

Paper

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by MqdGm** [comment]
any fix huh?

**Comment by spartacus04** [comment]
Fixed in 2.1
