### ISSUE TITLE
[BUG] Plugin can't running on Purpur

### ISSUE THREAD

**Issue by KanameOrion** [spartacus04/jext-reborn#47]
I'm currently running on Purpur 1.19.2-1824. Plugin won't load with this error

```
[21:24:46 INFO]: [PlaceholderAPI] Successfully registered expansion: tdrplaytime [1.11.3]
[21:24:46 INFO]: [JukeboxExtendedReborn] Enabling JukeboxExtendedReborn v0.7b
[21:24:46 INFO]: discs.json file does not exist, generate it with the provided tool
[21:24:46 INFO]: [JukeboxExtendedReborn] Disabling JukeboxExtendedReborn v0.7b
[21:24:46 INFO]: [Jext] Disabled Jukebox Extender Reborn, Mi Re Do!
[21:24:46 ERROR]: Error occurred while enabling JukeboxExtendedReborn v0.7b (Is it up to date?)
java.lang.NoClassDefFoundError: me/spartacus04/jext/config/ConfigManager$Companion$load$configType$1
        at me.spartacus04.jext.config.ConfigManager$Companion.load(ConfigManager.kt:47) ~[JEXT-Reborn_0.7b (1).jar:?]
        at me.spartacus04.jext.Jext.load(Jext.kt:36) ~[JEXT-Reborn_0.7b (1).jar:?]
        at me.spartacus04.jext.Jext.onEnable(Jext.kt:16) ~[JEXT-Reborn_0.7b (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.spartacus04.jext.config.ConfigManager$Companion$load$configType$1
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more
[21:24:46 INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.3
[21:24:46 INFO]: [SkinsRestorer] Detected Minecraft v1_19_R1, using PaperSkinRefresher.
```

And this is my plugin installed
```
[21:30:34 INFO]: Plugins (47): AdvancedBan, AuthMe, Citizens, CitizensGUI, CommandPanels, CoreProtect, DailyRewards, DecentHolograms, Denizen, dtlTraders, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExecutableItems, GSit, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, ItemEdit, JukeboxExtendedReborn, LevelledMobs, LockettePro, LuckPerms, Maintenance, MOTD, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, NBTAPI, NexEngine, Orebfuscator, Parkour, PlaceholderAPI, PowerCamera, ProtocolLib, RedProtect, RewardsLite, SCore, SkinsRestorer, spark, SuperVanish, TAB, TangledMaze, TDRPlaytime*, Vault, Vouchers
```

**Comment by spartacus04** [comment]
Fixed in latest release
