### ISSUE TITLE
There are some problems with the plugin.

### ISSUE THREAD

**Issue by rmr4k** [spartacus04/jext-reborn#5]
======================================
[19:37:57 INFO]: [JukeboxExtendedReborn] Enabling JukeboxExtendedReborn v1.0
[19:37:57 WARN]: me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.JsonSyntaxException: me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.stream.MalformedJsonException: Unterminated object at line 3 column 38 path $.now-playing-no-author
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.Gson.fromJson(Gson.java:1006)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.Gson.fromJson(Gson.java:956)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.Gson.fromJson(Gson.java:905)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.config.ConfigManager$Companion.deserialize(ConfigManager.kt:35)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.config.ConfigManager$Companion.load(ConfigManager.kt:67)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.Jext.load(Jext.kt:31)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.Jext.onEnable(Jext.kt:11)
[19:37:57 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:37:57 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:37:57 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[19:37:57 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[19:37:57 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[19:37:57 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[19:37:57 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[19:37:57 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[19:37:57 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
[19:37:57 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[19:37:57 WARN]: at java.base/java.lang.Thread.run(Unknown Source)
[19:37:57 WARN]: Caused by: me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.stream.MalformedJsonException: Unterminated object at line 3 column 38 path $.now-playing-no-author
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
[19:37:57 WARN]: at JukeboxExtendedReborn_0.3.jar//me.spartacus04.jext.dependencies.jukebox-extended-reborn.gson.Gson.fromJson(Gson.java:991)
[19:37:57 WARN]: ... 17 more
======================================

======================================
[19:42:31 INFO]: test_player issued server command: /jukeboxextendedreborn:disc
[19:42:31 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'jukeboxextendedreborn:discgive' in plugin JukeboxExtendedReborn v1.0 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
at java.lang.Thread.run(Unknown Source) ~[?:?]
======================================

**Comment by spartacus04** [comment]
Hi, I noticed that you already closed the issue, did you manage to fix the problem?
If you didn't don't hesitate to re-open the issue
