### ISSUE TITLE
[Bug]: Fails to load in server (Spigot 1.19 - Apex Hosting)

### ISSUE THREAD

**Issue by MonstaDash** [spartacus04/jext-reborn#97]
### Describe the bug

Whenever loading the plugin, it fails to load and ends up disabled. I am using Apex Hosting with spigot and 1.19.

### Steps to reproduce

27.04 23:12:43 [Server] Server thread/INFO [JEXT] Enabling JukeboxExtendedReborn v1.1.2
27.04 23:12:43 [Server] Server thread/WARN java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
27.04 23:12:43 [Server] Server thread/WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
27.04 23:12:43 [Server] Server thread/WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
27.04 23:12:43 [Server] Server thread/WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
27.04 23:12:43 [Server] Server thread/WARN at java.base/java.util.Objects.checkIndex(Objects.java:361)
27.04 23:12:43 [Server] Server thread/WARN at java.base/java.util.ArrayList.get(ArrayList.java:427)
27.04 23:12:43 [Server] Server thread/WARN at me.spartacus04.jext.SpigotVersion$Companion.load(SpigotVersion.kt:15)
27.04 23:12:43 [Server] Server thread/WARN at me.spartacus04.jext.Jext.load(Jext.kt:30)
27.04 23:12:43 [Server] Server thread/WARN at me.spartacus04.jext.Jext.onEnable(Jext.kt:16)
27.04 23:12:43 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
27.04 23:12:43 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
27.04 23:12:43 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
27.04 23:12:43 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:523)
27.04 23:12:43 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:437)
27.04 23:12:43 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582)
27.04 23:12:43 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401)
27.04 23:12:43 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255)
27.04 23:12:43 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966)
27.04 23:12:43 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
27.04 23:12:43 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)
27.04 23:12:43 [Server] Server thread/INFO [JEXT] Disabling JukeboxExtendedReborn v1.1.2
27.04 23:12:43 [Server] Server thread/INFO [JEXT] Disabled Jukebox Extended Reborn, Mi Re Do!

### Expected behaviour

For the plugin not to disable

### Server Version

1.19

### Server Type

Spigot

### Discs.json

```json
[
  {
    "title": "Coconut Mall",
    "author": "Shiho Fujii, Atsuko Asahi Ryo Nagamatsu, Yasuaki Iwata",
    "duration": 136,
    "disc-namespace": "music_disc.coconutmallshihofujiiatsukoasahiryonagamatsuyasuakiiwatazero",
    "model-data": 1,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": [
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small"
    ]
  },
  {
    "title": "Route 47",
    "author": "Takuto Kitsuta",
    "duration": 74,
    "disc-namespace": "music_disc.routefourseventakutokitsutaone",
    "model-data": 2,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Tears Of Father ~Overseas Edition~",
    "author": "Hidenori Shoji",
    "duration": 275,
    "disc-namespace": "music_disc.tearsoffatheroverseaseditionhidenorishojitwo",
    "model-data": 3,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [
      "chests/end_city_treasure"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "A Spartan Rises",
    "author": "Martin O'Donnell, Michael Salvatori, Paul Lipson, Lennie Moore, Tom Salta, Brian Trifon, Brian Lee White",
    "duration": 131,
    "disc-namespace": "music_disc.aspartanrisesmartinodonnellmichaelsalvatoripaullipsonlenniemooretomsaltabriantrifonbrianleewhitethree",
    "model-data": 4,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [
      "chests/stronghold_corridor",
      "chests/stronghold_crossing"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Masked and Wild: D.D.D.",
    "author": "Hirokazu Ando, Yuuta Ogasawara, Jun Ishikawa, Yuki Shimooka",
    "duration": 82,
    "disc-namespace": "music_disc.maskedandwilddddhirokazuandoyuutaogasawarajunishikawayukishimookafour",
    "model-data": 5,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/desert_pyramid"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "The Battle of Blizzard Bridge",
    "author": "Hirokazu Ando, Yuuta Ogasawara, Jun Ishikawa, Yuki Shimooka",
    "duration": 664,
    "disc-namespace": "music_disc.thebattleofblizzardbridgehirokazuandoyuutaogasawarajunishikawayukishimookafive",
    "model-data": 6,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/igloo_chest"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "It Has To Be This Way",
    "author": "Jimmy Gnecco",
    "duration": 176,
    "disc-namespace": "music_disc.ithastobethiswayjimmygneccosix",
    "model-data": 7,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/ancient_city",
      "chests/ancient_city_ice_box"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Break Off",
    "author": "Yuri Fukuda",
    "duration": 291,
    "disc-namespace": "music_disc.breakoffyurifukudaseven",
    "model-data": 8,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/ruined_portal",
      "chests/nether_bridge"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Knight of the Wind",
    "author": "Crush 40",
    "duration": 232,
    "disc-namespace": "music_disc.knightofthewindcrushfourzeroeight",
    "model-data": 9,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Watch Me Fly...",
    "author": "Crush 40",
    "duration": 312,
    "disc-namespace": "music_disc.watchmeflycrushfourzeronine",
    "model-data": 10,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [
      "chests/end_city_treasure"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Banana Jungle",
    "author": "Disc Author",
    "duration": 157,
    "disc-namespace": "music_disc.bananajunglediscauthoronezero",
    "model-data": 11,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/jungle_temple"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Lake",
    "author": "Shota Kageyama",
    "duration": 146,
    "disc-namespace": "music_disc.lakeshotakageyamaoneone",
    "model-data": 12,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/shipwreck_map",
      "chests/shipwreck_supply",
      "chests/shipwreck_treasure",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Alabaster Icelands 1 (Alternate Ver.)",
    "author": "Go Ichinose, Hitomi Sato, Hiromitsu Maeba & GAME FREAK",
    "duration": 158,
    "disc-namespace": "music_disc.alabastericelandsonealternatevergoichinosehitomisatohiromitsumaebagamefreakonetwo",
    "model-data": 13,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/igloo_chest",
      "chests/village/village_plains_house",
      "chests/village/village_savanna_house",
      "chests/village/village_desert_house",
      "chests/village/village_snowy_house",
      "chests/village/village_taiga_house"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Menu - Super Smash Bros. Melee (Brawl)",
    "author": "Motoi Sakuraba",
    "duration": 208,
    "disc-namespace": "music_disc.menusupersmashbrosmeleebrawlmotoisakurabaonethree",
    "model-data": 14,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Let the Battles Begin! - Battle Medley",
    "author": "Shotaro Shima",
    "duration": 198,
    "disc-namespace": "music_disc.letthebattlesbeginbattlemedleyshotaroshimaonefour",
    "model-data": 15,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [],
    "fragment-loot-tables": []
  },
  {
    "title": "Arise in Valor",
    "author": "Martin O'Donnell, Michael Salvatori, Paul Lipson, Lennie Moore, Tom Salta, Brian Trifon, Brian Lee White",
    "duration": 190,
    "disc-namespace": "music_disc.ariseinvalormartinodonnellmichaelsalvatoripaullipsonlenniemooretomsaltabriantrifonbrianleewhiteonefive",
    "model-data": 16,
    "creeper-drop": false,
    "lores": [],
    "loot-tables": [
      "chests/woodland_mansion",
      "chests/pillager_outpost"
    ],
    "fragment-loot-tables": []
  },
  {
    "title": "Wreckage",
    "author": "Kazuma Jinnouchi",
    "duration": 204,
    "disc-namespace": "music_disc.wreckagekazumajinnouchionesix",
    "model-data": 17,
    "creeper-drop": true,
    "lores": [],
    "loot-tables": [
      "chests/bastion_bridge",
      "chests/bastion_hoglin_treasure",
      "chests/bastion_other",
      "chests/bastion_treasure",
      "chests/ancient_city",
      "chests/ancient_city_ice_box",
      "chests/abandoned_mineshaft",
      "chests/stronghold_corridor",
      "chests/stronghold_crossing",
      "chests/underwater_ruin_big",
      "chests/underwater_ruin_small",
      "chests/ruined_portal"
    ],
    "fragment-loot-tables": []
  }
]
```

### Resource pack

https://drive.google.com/file/d/1PuVNNPIXrbTAL5vgTeLul0Q8AJSp0b2s/view?usp=sharing

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Hi, thanks for the bug report. I just fixed this in the 1.1.3 update, in case that happens again please reopen this issue
